import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const appleSDGothic = localFont({
  src: "./fonts/AppleSDGothicNeo.woff",
  variable: "--font-apple-gotic",
  weight: "400 700 600 100S",
});

export const metadata = {
  title: "Site",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` ${appleSDGothic.variable}`}>
        <Header />
        <div className="container">{children}</div>
      </body>
    </html>
  );
}
